shell /usr/bin/fish

background_opacity 0.5
background_blur 1

window_margin_width 0
window_padding_width 5

cursor_shape beam
cursor_beam_thickness 1

font_family JetBrainsMono Nerd Font
font_size 14

remember_window_size no
initial_window_width  100c
initial_window_height 50c

hide_window_decorations yes

include current-theme.conf
